### ISSUE TITLE
css breakes nova styling

### ISSUE THREAD

**Issue by niekdemelker** [ferdiunal/nova-settings#3]
Love this package, only noticed one problem with the css. The actions drop down appears twice now.

![afbeelding](https://github.com/user-attachments/assets/5dbc8818-b917-44b6-82d1-6e61d32b291e)

I found that removing the tailwind lines from the css fixes this problem...

```css
@tailwind base;
@tailwind components;
@tailwind utilities;
```

**Comment by ferdiunal** [comment]
Hi 👋, I'm glad you like the package 🙏, I think we broke something 😅, I'll make the necessary improvement and fix it.
