### ISSUE TITLE
v1.0.9 with Commit 682f249?

### ISSUE THREAD

**Issue by joserick** [ferdiunal/nova-settings#5]
Hi,

I see that a week ago you released version 1.0.8 but at the same time you released the commit [Refactor code for improved readability and maintainability, and add policy support](https://github.com/ferdiunal/nova-settings/commit/682f249ca172a642235bfcdb9623ab32debfc1d4) Would you have a date to release version 1.0.9 with these changes since currently in my projects we're not handling Spatie Laravel-Permission.

**Comment by ferdiunal** [comment]
Hi, I'm sorry about the problem you're having. I have made the necessary corrections and released the new version.
