### ISSUE TITLE
Input type "File" multiple

### ISSUE THREAD

**Issue by joserick** [ferdiunal/nova-settings#6]
Hello,

I am using a Nova Packages field which is a input of type file multiple, it sends the information but it is not stored.

In SettingsController on [linea 107](https://github.com/ferdiunal/nova-settings/blob/32d084286956a0b2700fdf342859584f68debf87/src/Http/Controllers/SettingsController.php#L107C1-L110C90) you fill the `$tempResource` variable based on the request but this process causes the value sent by the input (multiple file) to become 3 values ​​leaving the main one empty and therefore not storing the value:

![Captura desde 2024-09-17 22-30-30](https://github.com/user-attachments/assets/7b6fe469-995e-4f37-a386-819c6d913e61)

**Comment by ferdiunal** [comment]
Hi, could you share the code you used with me. To get a more accurate result.

**Comment by joserick** [comment]
I think the problem is the field I'm using [Filepond](https://novapackages.com/packages/digital-creative/nova-filepond), this sends the information with the name="banner[]"

![Captura desde 2024-09-18 01-25-41](https://github.com/user-attachments/assets/64fceb68-22a9-4971-8383-bda4b6053c4f)

And indeed the `request()` obtains it as an array:

![imagen](https://github.com/user-attachments/assets/2b137e39-2df7-4f64-ba4e-07ce5ab2ba9b)

But when filling `tempResource` using the `fill` method of the field, which in this case is "Filepond", it sets the values ​​separately:
![imagen](https://github.com/user-attachments/assets/e3f3b1d4-154e-4167-b5e1-9c876a59ff61)

In case you want to do tests with Filepond I recommend you comment or delete the following [lineas](https://github.com/dcasia/nova-filepond/blob/d2301c01e17da3fa2fff4a9ea3cddef7c9511af2/src/Http/Controllers/ProcessController.php#L44C9-L79C1) since this uses `Nova::resourceInstanceForKey($resourceName)` to perform validations based on "Nova Resources" but your `SettingResource` do not inherit from this or that is what I understand.

**Comment by joserick** [comment]
I understand now, this is a Filepond problem of the [fillAttribute](https://github.com/dcasia/nova-filepond/blob/d2301c01e17da3fa2fff4a9ea3cddef7c9511af2/src/Filepond.php#L137C5-L210C16) function, thanks for your support.
